In [1]:
# 轉照片
import cv2
import time
import numpy as np
import math
img_path = 'D:\opcv\lena.png'

# 以彩色圖片的方式載入
img = cv2.imread(img_path, cv2.IMREAD_COLOR)

# 設定 translation transformation matrix
# x 平移 100 pixel; y 平移 50 pixel
a=math.sin(45*math.pi/180)
b=math.cos(45*math.pi/180)
M = np.array([[b, -a, 0],
              [a, b, 0]], dtype=np.float32)
#img = cv2.resize(img, None, fx=0.5, fy=0.5)
shift_img = cv2.warpAffine(img, M, (512, 512))

print(img.shape[1],img.shape[0])

# 組合 + 顯示圖片

while True:
    cv2.imshow('shift_img', shift_img)
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

512 512


In [21]:
import cv2
import time
import numpy as np
import math
print(math.sin(45*math.pi/180))


0.7071067811865476


In [2]:
import cv2
import time
import numpy as np
import math

img_path = 'D:\opcv\lena.png'
# 以彩色圖片的方式載入
img = cv2.imread(img_path, cv2.IMREAD_COLOR)
rows,cols=img.shape[:2]

#这里的第一个参数为旋转中心，第二个为旋转角度，第三个为旋转后的缩放因子
#可以通过设置旋转中心，缩放因子以及窗口大小来防止旋转后超出边界的问题。
M=cv2.getRotationMatrix2D((cols/2,rows/2),45,0.5)
print(M)
#第三个参数是输出图像的尺寸中心
dst=cv2.warpAffine(img,M,(cols,rows))
while(1):
    cv2.imshow('img',dst)
    cv2.imshow('imgimg',img)
    if cv2.waitKey(1)==27:
        break
cv2.destroyAllWindows()

[[  0.35355339   0.35355339  74.98066402]
 [ -0.35355339   0.35355339 256.        ]]


In [5]:
import cv2
import time
import numpy as np
import math

img_path = 'D:\opcv\lena.png'
# 以彩色圖片的方式載入
img = cv2.imread(img_path, cv2.IMREAD_COLOR)


rows, cols = img.shape[:2]
pt1 = np.array([[50,50], [300,100], [200,300]], dtype=np.float32)
pt2 = np.array([[80,80], [330,150], [300,300]], dtype=np.float32)

# 取得 affine 矩陣並做 affine 操作
M_affine = cv2.getAffineTransform(pt1,pt2)
img_affine = cv2.warpAffine(img,M_affine,(2*cols,2*rows))
print(M_affine)

# 在圖片上標記點
img_copy = img.copy()
#座標點分別提取出來
for idx, pts in enumerate(pt1):
    #座標點提取改成整數
    pts = tuple(map(int, pts))
    #在座標上畫圈
    cv2.circle(img_copy, pts, 3, (0, 255, 0), -1)
    #在座標上標數字
    cv2.putText(img_copy, str(idx), (pts[0]+5, pts[1]+5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)

for idx, pts in enumerate(pt2):
    pts = tuple(map(int, pts))
    cv2.circle(img_affine, pts, 3, (0, 255, 0), -1)
    cv2.putText(img_affine, str(idx), (pts[0]+5, pts[1]+5), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 1)


while True:
    cv2.imshow('affine transformation', img_copy )
    cv2.imshow('img_affine', img_affine )
    if cv2.waitKey(1)==27:
        break
cv2.destroyAllWindows()


[[ 0.93636364  0.31818182 17.27272727]
 [ 0.11818182  0.80909091 33.63636364]]
